"""
games/terraria/config.py — Lecture/écriture de serverconfig.txt.
"""
import os
from flask import current_app


def _cfg_path():
    install_dir = current_app.config['GAME']['server']['install_dir']
    return os.path.join(install_dir, 'serverconfig.txt')


def _defaults():
    game = current_app.config['GAME']
    data_dir = game['server'].get('data_dir') or game['server']['install_dir']
    world_name = game['id']
    return {
        'world': os.path.join(data_dir, f'{world_name}.wld'),
        'worldpath': data_dir,
        'worldname': world_name,
        'autocreate': '2',
        'difficulty': '0',
        'port': str(game['server'].get('port', 7777)),
        'maxplayers': str(game['server'].get('max_players', 8)),
        'password': '',
        'motd': game['name'],
        'seed': '',
        'banlist': 'banlist.txt',
        'secure': '1',
        'noupnp': '0',
        'steam': '1',
        'lobby': 'friends',
        'ip': '',
        'forcepriority': '0',
        'disableannouncementbox': '0',
        'announcementboxrange': '0',
    }


def _parse_cfg(path):
    data = {}
    with open(path, encoding='utf-8') as f:
        for raw_line in f:
            line = raw_line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, value = line.split('=', 1)
            data[key.strip()] = value.strip()
    return data


def read_config():
    path = _cfg_path()
    data = _defaults()
    if os.path.exists(path):
        try:
            data.update(_parse_cfg(path))
        except Exception as e:
            return {}, str(e)
    return data, None


def write_config(new_data):
    path = _cfg_path()
    try:
        current, err = read_config()
        if err:
            return False, err

        current.update({k: str(v) for k, v in (new_data or {}).items() if v is not None})
        worldpath = current.get('worldpath', '').strip()
        worldname = current.get('worldname', '').strip()
        if worldpath and worldname:
            current['world'] = os.path.join(worldpath, f'{worldname}.wld')
        ok, err = _validate(current)
        if not ok:
            return False, err

        os.makedirs(os.path.dirname(path), exist_ok=True)
        lines = [
            '# Terraria server config',
            '# Generated by Game Commander',
        ]
        ordered_keys = [
            'world', 'worldpath', 'worldname', 'autocreate', 'difficulty',
            'port', 'maxplayers', 'password', 'motd',
            'seed', 'banlist', 'secure', 'noupnp', 'steam', 'lobby', 'ip',
            'forcepriority', 'disableannouncementbox', 'announcementboxrange',
        ]
        for key in ordered_keys:
            lines.append(f'{key}={current.get(key, "")}')
        with open(path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines) + '\n')
        return True, None
    except Exception as e:
        return False, str(e)


def _validate(data):
    ints = {
        'port': (1, 65535),
        'maxplayers': (1, 255),
        'autocreate': (1, 3),
        'difficulty': (0, 3),
        'secure': (0, 1),
        'noupnp': (0, 1),
        'steam': (0, 1),
        'forcepriority': (0, 1),
        'disableannouncementbox': (0, 1),
        'announcementboxrange': (0, 10000),
    }
    for key, (min_v, max_v) in ints.items():
        try:
            value = int(data.get(key, 0))
        except ValueError:
            return False, f'{key} doit être un entier'
        if not (min_v <= value <= max_v):
            return False, f'{key} doit être entre {min_v} et {max_v}'

    if not data.get('worldpath', '').strip():
        return False, 'worldpath requis'
    if not data.get('worldname', '').strip():
        return False, 'worldname requis'
    lobby = (data.get('lobby') or '').strip().lower()
    if lobby and lobby not in {'friends', 'private'}:
        return False, 'lobby doit être friends ou private'
    return True, None


def get_schema():
    return [
        {'key': 'worldname', 'label': 'Nom du monde', 'type': 'text'},
        {'key': 'motd', 'label': 'MOTD', 'type': 'text'},
        {'key': 'maxplayers', 'label': 'Joueurs max', 'type': 'number', 'min': 1, 'max': 255},
        {'key': 'password', 'label': 'Mot de passe', 'type': 'password'},
        {'key': 'autocreate', 'label': 'Taille du monde', 'type': 'select', 'options': ['1', '2', '3']},
        {'key': 'difficulty', 'label': 'Difficulté', 'type': 'select', 'options': ['0', '1', '2', '3']},
        {'key': 'port', 'label': 'Port', 'type': 'number', 'min': 1, 'max': 65535},
        {'key': 'seed', 'label': 'Seed', 'type': 'text'},
        {'key': 'banlist', 'label': 'Banlist', 'type': 'text'},
        {'key': 'secure', 'label': 'Mode sécurisé', 'type': 'select', 'options': ['0', '1']},
        {'key': 'noupnp', 'label': 'Désactiver UPnP', 'type': 'select', 'options': ['0', '1']},
        {'key': 'steam', 'label': 'Activer Steam', 'type': 'select', 'options': ['0', '1']},
        {'key': 'lobby', 'label': 'Lobby', 'type': 'select', 'options': ['friends', 'private']},
        {'key': 'ip', 'label': 'IP d’écoute', 'type': 'text'},
        {'key': 'forcepriority', 'label': 'Priorité forcée', 'type': 'select', 'options': ['0', '1']},
        {'key': 'disableannouncementbox', 'label': 'Désactiver announcement box', 'type': 'select', 'options': ['0', '1']},
        {'key': 'announcementboxrange', 'label': 'Portée announcement box', 'type': 'number', 'min': 0, 'max': 10000},
    ]
