"""
games/minecraft/config.py — Lecture/écriture de server.properties.
"""
import os
from flask import current_app


def _cfg_path():
    install_dir = current_app.config['GAME']['server']['install_dir']
    return os.path.join(install_dir, 'server.properties')


def _defaults():
    game = current_app.config['GAME']
    return {
        'motd': game['name'],
        'server-port': str(game['server'].get('port', 25565)),
        'max-players': str(game['server'].get('max_players', 20)),
        'gamemode': 'survival',
        'difficulty': 'easy',
        'pvp': 'true',
        'allow-nether': 'true',
        'enable-command-block': 'false',
        'spawn-monsters': 'true',
        'spawn-animals': 'true',
        'view-distance': '10',
        'simulation-distance': '10',
    }


def _parse_properties(path):
    data = {}
    with open(path, encoding='utf-8') as f:
        for raw_line in f:
            line = raw_line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, value = line.split('=', 1)
            data[key.strip()] = value.strip()
    return data


def read_config():
    path = _cfg_path()
    data = _defaults()
    if os.path.exists(path):
        try:
            data.update(_parse_properties(path))
        except Exception as e:
            return {}, str(e)
    return {'Server': data}, None


def write_config(new_data):
    path = _cfg_path()
    try:
        current, err = read_config()
        if err:
            return False, err

        server = current.get('Server', {})
        updates = (new_data or {}).get('Server', {})
        server.update({k: str(v) for k, v in updates.items() if v is not None})

        ok, err = _validate(server)
        if not ok:
            return False, err

        os.makedirs(os.path.dirname(path), exist_ok=True)
        lines = [
            '# Minecraft server properties',
            '# Generated by Game Commander',
        ]
        for key in sorted(server):
            lines.append(f'{key}={server[key]}')
        with open(path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines) + '\n')
        return True, None
    except Exception as e:
        return False, str(e)


def _validate(server):
    ints = {
        'server-port': (1, 65535),
        'max-players': (1, 1000),
        'view-distance': (2, 32),
        'simulation-distance': (2, 32),
    }
    for key, (min_v, max_v) in ints.items():
        try:
            value = int(server.get(key, 0))
        except ValueError:
            return False, f'{key} doit être un entier'
        if not (min_v <= value <= max_v):
            return False, f'{key} doit être entre {min_v} et {max_v}'

    enums = {
        'difficulty': {'peaceful', 'easy', 'normal', 'hard'},
        'gamemode': {'survival', 'creative', 'adventure', 'spectator'},
    }
    for key, allowed in enums.items():
        if server.get(key, '') not in allowed:
            return False, f'{key} invalide'

    for key in {
        'pvp', 'allow-nether', 'enable-command-block',
        'spawn-monsters', 'spawn-animals',
    }:
        if server.get(key, '') not in {'true', 'false'}:
            return False, f'{key} doit être true ou false'

    return True, None


def get_schema():
    return [
        {'key': 'max-players', 'label': 'Joueurs max', 'type': 'number', 'min': 1, 'max': 1000},
        {'key': 'difficulty', 'label': 'Difficulté', 'type': 'select',
         'options': ['peaceful', 'easy', 'normal', 'hard']},
        {'key': 'gamemode', 'label': 'Mode de jeu', 'type': 'select',
         'options': ['survival', 'creative', 'adventure', 'spectator']},
        {'key': 'pvp', 'label': 'PvP', 'type': 'select', 'options': ['true', 'false']},
        {'key': 'allow-nether', 'label': 'Nether', 'type': 'select', 'options': ['true', 'false']},
        {'key': 'enable-command-block', 'label': 'Command blocks', 'type': 'select', 'options': ['true', 'false']},
        {'key': 'spawn-monsters', 'label': 'Monstres', 'type': 'select', 'options': ['true', 'false']},
        {'key': 'spawn-animals', 'label': 'Animaux', 'type': 'select', 'options': ['true', 'false']},
        {'key': 'view-distance', 'label': 'Distance de vue', 'type': 'number', 'min': 2, 'max': 32},
        {'key': 'simulation-distance', 'label': 'Distance simulation', 'type': 'number', 'min': 2, 'max': 32},
        {'key': 'motd', 'label': 'MOTD', 'type': 'text'},
    ]
