"""
games/minecraft/config.py — Lecture/écriture de server.properties.
"""
import os
from flask import current_app


def _cfg_path():
    install_dir = current_app.config['GAME']['server']['install_dir']
    return os.path.join(install_dir, 'server.properties')


def _defaults():
    game = current_app.config['GAME']
    return {
        'motd': game['name'],
        'server-port': str(game['server'].get('port', 25565)),
        'max-players': str(game['server'].get('max_players', 20)),
        'online-mode': 'true',
        'hide-online-players': 'false',
        'player-idle-timeout': '0',
        'gamemode': 'survival',
        'difficulty': 'easy',
        'hardcore': 'false',
        'pvp': 'true',
        'force-gamemode': 'false',
        'allow-flight': 'false',
        'allow-nether': 'true',
        'enable-command-block': 'false',
        'spawn-monsters': 'true',
        'spawn-animals': 'true',
        'spawn-protection': '16',
        'view-distance': '10',
        'simulation-distance': '10',
        'max-world-size': '29999984',
        'white-list': 'false',
        'enforce-whitelist': 'false',
        'op-permission-level': '4',
        'enable-query': 'false',
        'query.port': str(game['server'].get('query_port', 25565)),
        'enable-rcon': 'false',
        'rcon.port': '25575',
        'rcon.password': '',
        'network-compression-threshold': '256',
        'max-tick-time': '60000',
        'resource-pack': '',
        'resource-pack-prompt': '',
        'require-resource-pack': 'false',
        'resource-pack-sha1': '',
    }


def _parse_properties(path):
    data = {}
    with open(path, encoding='utf-8') as f:
        for raw_line in f:
            line = raw_line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, value = line.split('=', 1)
            data[key.strip()] = value.strip()
    return data


def read_config():
    path = _cfg_path()
    data = _defaults()
    if os.path.exists(path):
        try:
            data.update(_parse_properties(path))
        except Exception as e:
            return {}, str(e)
    return {'Server': data}, None


def write_config(new_data):
    path = _cfg_path()
    try:
        current, err = read_config()
        if err:
            return False, err

        server = current.get('Server', {})
        updates = (new_data or {}).get('Server', {})
        server.update({k: str(v) for k, v in updates.items() if v is not None})

        ok, err = _validate(server)
        if not ok:
            return False, err

        os.makedirs(os.path.dirname(path), exist_ok=True)
        lines = [
            '# Minecraft server properties',
            '# Generated by Game Commander',
        ]
        for key in sorted(server):
            lines.append(f'{key}={server[key]}')
        with open(path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines) + '\n')
        return True, None
    except Exception as e:
        return False, str(e)


def _validate(server):
    ints = {
        'server-port': (1, 65535),
        'max-players': (1, 1000),
        'player-idle-timeout': (0, 2147483647),
        'spawn-protection': (0, 64),
        'view-distance': (2, 32),
        'simulation-distance': (2, 32),
        'max-world-size': (1, 29999984),
        'op-permission-level': (1, 4),
        'query.port': (1, 65535),
        'rcon.port': (1, 65535),
        'network-compression-threshold': (-1, 2147483647),
        'max-tick-time': (-1, 2147483647),
    }
    for key, (min_v, max_v) in ints.items():
        try:
            value = int(server.get(key, 0))
        except ValueError:
            return False, f'{key} doit être un entier'
        if not (min_v <= value <= max_v):
            return False, f'{key} doit être entre {min_v} et {max_v}'

    enums = {
        'difficulty': {'peaceful', 'easy', 'normal', 'hard'},
        'gamemode': {'survival', 'creative', 'adventure', 'spectator'},
    }
    for key, allowed in enums.items():
        if server.get(key, '') not in allowed:
            return False, f'{key} invalide'

    for key in {
        'pvp', 'allow-nether', 'enable-command-block',
        'spawn-monsters', 'spawn-animals', 'online-mode',
        'hide-online-players', 'hardcore', 'force-gamemode',
        'allow-flight', 'white-list', 'enforce-whitelist',
        'enable-query', 'enable-rcon', 'require-resource-pack',
    }:
        if server.get(key, '') not in {'true', 'false'}:
            return False, f'{key} doit être true ou false'

    return True, None


def get_schema():
    return [
        {'section': 'Serveur', 'key': 'motd', 'label': 'MOTD', 'type': 'text'},
        {'section': 'Serveur', 'key': 'max-players', 'label': 'Joueurs max', 'type': 'number', 'min': 1, 'max': 1000},
        {'section': 'Serveur', 'key': 'online-mode', 'label': 'Online mode', 'type': 'select', 'options': ['true', 'false']},
        {'section': 'Serveur', 'key': 'hide-online-players', 'label': 'Masquer la liste des joueurs', 'type': 'select', 'options': ['true', 'false']},
        {'section': 'Serveur', 'key': 'player-idle-timeout', 'label': 'Timeout AFK', 'type': 'number', 'min': 0, 'max': 2147483647},
        {'section': 'Gameplay', 'key': 'gamemode', 'label': 'Mode de jeu', 'type': 'select', 'options': ['survival', 'creative', 'adventure', 'spectator']},
        {'section': 'Gameplay', 'key': 'difficulty', 'label': 'Difficulté', 'type': 'select', 'options': ['peaceful', 'easy', 'normal', 'hard']},
        {'section': 'Gameplay', 'key': 'hardcore', 'label': 'Hardcore', 'type': 'select', 'options': ['true', 'false']},
        {'section': 'Gameplay', 'key': 'pvp', 'label': 'PvP', 'type': 'select', 'options': ['true', 'false']},
        {'section': 'Gameplay', 'key': 'force-gamemode', 'label': 'Forcer le mode de jeu', 'type': 'select', 'options': ['true', 'false']},
        {'section': 'Gameplay', 'key': 'allow-flight', 'label': 'Autoriser le vol', 'type': 'select', 'options': ['true', 'false']},
        {'section': 'Monde', 'key': 'allow-nether', 'label': 'Nether', 'type': 'select', 'options': ['true', 'false']},
        {'section': 'Monde', 'key': 'enable-command-block', 'label': 'Command blocks', 'type': 'select', 'options': ['true', 'false']},
        {'section': 'Monde', 'key': 'spawn-monsters', 'label': 'Monstres', 'type': 'select', 'options': ['true', 'false']},
        {'section': 'Monde', 'key': 'spawn-animals', 'label': 'Animaux', 'type': 'select', 'options': ['true', 'false']},
        {'section': 'Monde', 'key': 'spawn-protection', 'label': 'Protection du spawn', 'type': 'number', 'min': 0, 'max': 64},
        {'section': 'Monde', 'key': 'view-distance', 'label': 'Distance de vue', 'type': 'number', 'min': 2, 'max': 32},
        {'section': 'Monde', 'key': 'simulation-distance', 'label': 'Distance simulation', 'type': 'number', 'min': 2, 'max': 32},
        {'section': 'Monde', 'key': 'max-world-size', 'label': 'Taille max du monde', 'type': 'number', 'min': 1, 'max': 29999984},
        {'section': 'Accès', 'key': 'white-list', 'label': 'Whitelist', 'type': 'select', 'options': ['true', 'false']},
        {'section': 'Accès', 'key': 'enforce-whitelist', 'label': 'Forcer la whitelist', 'type': 'select', 'options': ['true', 'false']},
        {'section': 'Accès', 'key': 'op-permission-level', 'label': 'Niveau OP', 'type': 'select', 'options': ['1', '2', '3', '4']},
        {'section': 'Réseau', 'key': 'enable-query', 'label': 'Activer Query', 'type': 'select', 'options': ['true', 'false']},
        {'section': 'Réseau', 'key': 'query.port', 'label': 'Port Query', 'type': 'number', 'min': 1, 'max': 65535},
        {'section': 'Réseau', 'key': 'enable-rcon', 'label': 'Activer RCON', 'type': 'select', 'options': ['true', 'false']},
        {'section': 'Réseau', 'key': 'rcon.port', 'label': 'Port RCON', 'type': 'number', 'min': 1, 'max': 65535},
        {'section': 'Réseau', 'key': 'rcon.password', 'label': 'Mot de passe RCON', 'type': 'text'},
        {'section': 'Réseau', 'key': 'network-compression-threshold', 'label': 'Seuil de compression', 'type': 'number', 'min': -1, 'max': 2147483647},
        {'section': 'Réseau', 'key': 'max-tick-time', 'label': 'Temps max par tick', 'type': 'number', 'min': -1, 'max': 2147483647},
        {'section': 'Ressources', 'key': 'resource-pack', 'label': 'URL resource pack', 'type': 'text'},
        {'section': 'Ressources', 'key': 'resource-pack-prompt', 'label': 'Message resource pack', 'type': 'text'},
        {'section': 'Ressources', 'key': 'require-resource-pack', 'label': 'Resource pack obligatoire', 'type': 'select', 'options': ['true', 'false']},
        {'section': 'Ressources', 'key': 'resource-pack-sha1', 'label': 'SHA1 resource pack', 'type': 'text'},
    ]
